# Generated by Django 3.2.9 on 2021-11-21 14:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default='NULL', max_length=350, size=6),
            preserve_default=False,
        ),
    ]
