# Generated by Django 3.2.9 on 2021-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211121_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lname',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='api.Author'),
        ),
    ]
